### ISSUE TITLE
setting oauth2 token

### ISSUE THREAD

**Issue by connor11528** [iamraphson/github-searcher#4]
Hey my bad I cloned the repo fresh and created a new **.env** file

```
TOKEN_SECRET=secretTokenh3re
GITHUB_SECRET=ed.......24e52a360e
```

But then when I spin it up get an error. What am I forgetting to add?

```
GET /api/search/react/10/1 500 36.287 ms - 1406
Error: OAuth2 authentication requires a token or key & secret to be set
    at __dirname.authenticate (/Users/connorleech/Projects/github-searcher/node_modules/github/lib/index.js:332:23)
    at authForGitApi (/Users/connorleech/Projects/github-searcher/server/controllers/Github.server.controller.js:50:12)
    at module.exports.searchRepo (/Users/connorleech/Projects/github-searcher/server/controllers/Github.server.controller.js:13:22)
    at Layer.handle [as handle_request] (/Users/connorleech/Projects/github-searcher/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/connorleech/Projects/github-searcher/node_modules/express/lib/router/route.js:131:13)
    at module.exports.ensureAuthenticated (/Users/connorleech/Projects/github-searcher/config/token.js:43:9)
    at Layer.handle [as handle_request] (/Users/connorleech/Projects/github-searcher/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/connorleech/Projects/github-searcher/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/connorleech/Projects/github-searcher/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/connorleech/Projects/github-searcher/node_modules/express/lib/router/layer.js:95:5)
```

Thank you!

**Comment by iamraphson** [comment]
Dear @connor11528 

Please try forking the repo again and let me know the error 

BR
Ayeni Olusegun
