### ISSUE TITLE
Documentation required

### ISSUE THREAD

**Issue by 0xbadshah** [iamraphson/github-searcher#6]
This is a great project, but lacks documentation. Can you please elaborate on what is `TOKEN_SECRET` in `.env` file ? How do you get `TOKEN_SECRET` and `GITHUB_SECRET` ? I tried several times and end up with the following error

```
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server`
module.js:327
    throw err;
``` 
Please give a sample of `.env` file

**Comment by iamraphson** [comment]
Dear @Chan9390 ,

Trust you are doing great..

in the repo, you will see a file called .env.example , that is sample for .env .you can rename it to .env
and put all you mongodb details, github client secret and token secret to help in hashing your password.

Go to public/js directory, you will see a file called app.js. go to line 18 then put you github client id 

Any issue, let me know...

Thanks

Ayeni Olusegun

**Comment by 0xbadshah** [comment]
What is `TOKEN_SECRET` ?

**Comment by iamraphson** [comment]
Dear @Chan9390 

TOKEN_SECRET is a random string of any length using in hashing the password in the application.

Cheers
Ayeni Olusegun

**Comment by 0xbadshah** [comment]
Cool. How do you represent MONGO_URL ? Is the format correct : `mongodb://localhost:27017/your_db`

**Comment by iamraphson** [comment]
Dear @Chan9390 

Yes,

Cheers

**Comment by 0xbadshah** [comment]
Thank you. But I still see the error: 
```

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server`
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/github-searcher/server/controllers/Auth.server.controller.js:7:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/github-searcher/server/routes.js:1:78)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by 0xbadshah** [comment]
Dont forget to add `npm install lodash --save` ( Pull request #7 )

**Comment by 0xbadshah** [comment]
It would be better if you have `Deploy on Heroku` button and a copy of `app.json`.

**Comment by iamraphson** [comment]
ok...thanks
